# Generated by Django 2.0.6 on 2018-06-19 16:43

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('T', 'Table'), ('H', 'Hand')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='InstantCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('R', 'Red'), ('G', 'Grey')], max_length=1)),
                ('value', models.IntegerField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instantcard_related', to='s51.Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaderCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=0)),
                ('instant_income', models.CharField(max_length=30)),
                ('reacts_to', models.CharField(max_length=30)),
                ('passive_income', models.CharField(max_length=30)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadercard_related', to='s51.Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction_name', models.CharField(max_length=25)),
                ('resources', picklefield.fields.PickledObjectField(default={'VP': 0, 'arrows': {'blue': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}, 'grey': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}, 'red': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}}, 'bricks': 0, 'fuel': 0, 'guns': 0, 'rebuilds': 0, 'steel': 0, 'universal': 0, 'workers': 0}, editable=False)),
                ('has_passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteCardAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=0)),
                ('conquest_income', models.CharField(max_length=50)),
                ('agreement_income', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=30)),
                ('action_cost', models.CharField(max_length=30)),
                ('action_income', models.CharField(max_length=30)),
                ('VP_tokens', models.IntegerField(default=0)),
                ('worker_cost', models.IntegerField(default=1)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardaction_related', to='s51.Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCardFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=0)),
                ('conquest_income', models.CharField(max_length=50)),
                ('agreement_income', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=30)),
                ('production_income', models.CharField(max_length=30)),
                ('is_opened', models.BooleanField(default=False)),
                ('times_visited', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardfactory_related', to='s51.Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCardPassive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('distance', models.IntegerField(default=0)),
                ('conquest_income', models.CharField(max_length=50)),
                ('agreement_income', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=30)),
                ('reacts_to', models.CharField(max_length=30)),
                ('passive_income', models.CharField(max_length=30)),
                ('VP_tokens', models.IntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardpassive_related', to='s51.Deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s51.Player'),
        ),
    ]
