# Generated by Django 2.0.6 on 2018-06-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leadercard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sitecardaction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sitecardfactory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sitecardpassive',
            name='name',
        ),
    ]
