# Generated by Django 2.0.6 on 2018-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0002_auto_20180619_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantcard',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='leadercard',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sitecardaction',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sitecardfactory',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sitecardpassive',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
