# Generated by Django 2.0.6 on 2018-06-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0003_auto_20180619_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantcard',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('grey', 'Grey')], max_length=1),
        ),
        migrations.AlterField(
            model_name='instantcard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instantcard_set', to='s51.Deck'),
        ),
        migrations.AlterField(
            model_name='leadercard',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadercard_set', to='s51.Deck'),
        ),
        migrations.AlterField(
            model_name='sitecardaction',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardaction_set', to='s51.Deck'),
        ),
        migrations.AlterField(
            model_name='sitecardfactory',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardfactory_set', to='s51.Deck'),
        ),
        migrations.AlterField(
            model_name='sitecardpassive',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitecardpassive_set', to='s51.Deck'),
        ),
    ]
