# Generated by Django 2.0.6 on 2018-06-19 19:59

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0004_auto_20180619_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='resources',
            field=picklefield.fields.PickledObjectField(default={'VP': 0, 'agreements': 0, 'arrows': {'blue': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}, 'grey': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}, 'red': {1: 0, 2: 0, 3: 0, 4: 0, 5: 0}}, 'bricks': 0, 'cards': 0, 'fuel': 0, 'guns': 0, 'rebuilds': 0, 'steel': 0, 'universal': 0, 'workers': 0}, editable=False),
        ),
    ]
