# Generated by Django 2.0.6 on 2018-06-20 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0005_auto_20180619_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecardaction',
            name='use_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='deck',
            name='kind',
            field=models.CharField(choices=[('T', 'Table'), ('H', 'Hand'), ('A', 'Agreements'), ('D', 'Discard'), ('P', 'Pile')], max_length=1),
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='s51.Player'),
        ),
    ]
