# Generated by Django 2.0.6 on 2018-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0006_auto_20180620_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='kind',
            field=models.CharField(choices=[('T', 'Table'), ('H', 'Hand'), ('A', 'Agreements'), ('D', 'Discard'), ('P', 'Pile'), ('S', 'To Spare'), ('L', 'Lookup')], max_length=1),
        ),
    ]
