# Generated by Django 2.0.6 on 2018-06-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0008_auto_20180620_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecardaction',
            name='agreement_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecardaction',
            name='categories',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitecardaction',
            name='conquest_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecardfactory',
            name='agreement_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecardfactory',
            name='categories',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitecardfactory',
            name='conquest_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecardpassive',
            name='agreement_income',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecardpassive',
            name='categories',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sitecardpassive',
            name='conquest_income',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
