# Generated by Django 2.0.6 on 2018-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0009_auto_20180620_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantcard',
            name='graphic',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='leadercard',
            name='graphic',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='sitecardaction',
            name='graphic',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='sitecardfactory',
            name='graphic',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
        migrations.AddField(
            model_name='sitecardpassive',
            name='graphic',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
    ]
