# Generated by Django 2.0.6 on 2018-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0010_auto_20180620_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(null=True, upload_to='cards/'),
        ),
    ]
