# Generated by Django 2.0.6 on 2018-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0011_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantcard',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('grey', 'Grey')], max_length=5),
        ),
    ]
