# Generated by Django 2.0.6 on 2018-06-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s51', '0013_auto_20180620_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('symbol', models.ImageField(upload_to='tokens/')),
            ],
        ),
    ]
